import type { Metadata } from "next";
import { Funnel_Display } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import { ClerkProvider } from '@clerk/nextjs';
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const appFont = Funnel_Display({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={appFont.className}>
          <Provider>{children}</Provider>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
